<?php

namespace Chiphpotle\Rest\Enum;


enum LookupPermissionship: string
{
    case UNSPECIFIED = 'LOOKUP_PERMISSIONSHIP_UNSPECIFIED';
    case HAS_PERMISSION = 'LOOKUP_PERMISSIONSHIP_HAS_PERMISSION';
    case CONDITIONAL_PERMISSION = 'LOOKUP_PERMISSIONSHIP_CONDITIONAL_PERMISSION';
}
